Shm
Martyna-Tu/object-oriented-programming pull request #27
Opened 2021-06-29 10:25 UTC by gyrydymptum

2021-06-29 11:39 UTC, Martyna-Tu commented on shm/Ship.cpp
> +    for (auto& el : cargoVec_) {
maybe  it will be better to switch "el" in range loop to "cargoOnBoard" - it is more readable

2021-06-29 11:42 UTC, Martyna-Tu commented on shm/Ship.cpp
> +            if (el->getAmount() - cargo->getAmount() > 0) {
it's the same, but looks better
cargoOnBoard->getAmount() > cargo->getAmount()

2021-06-30 16:00 UTC, runer53248 requested changes

2021-06-30 16:00 UTC, runer53248 commented on shm/Ship.cpp
> +    cargoVec_.erase(std::remove_if(cargoVec_.begin(), cargoVec_.end(),
If cargo->getAmount() > cargoOnBoard->getAmount() we will remove-erase less than expected.
If cargoVec_ contain empty unique_ptr then remove_if dereference nullptr when call *cargoOnBoard.
Remove-Erase part can remove more than one Cargo if there are comperable similiar in cargoVec_.
We cant't take unloaded cargo and have no idea it's success.

2021-07-01 11:02 UTC, closed without merging